using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NMatrix.Schematron.Serialization
{
    /// <summary>
    /// <remarks>
    /// This code was generated by VS Paste Special Xml to Class. It therefore may feel like overkill and a poor model to support deserialization operations
    /// </remarks>
    /// </summary>
    public class SchematronValidationResultTempObjectModel
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron", IsNullable = false)]
        public partial class output
        {

            private outputXml xmlField;

            private outputSchematron schematronField;

            /// <remarks/>
            public outputXml xml
            {
                get
                {
                    return this.xmlField;
                }
                set
                {
                    this.xmlField = value;
                }
            }

            /// <remarks/>
            public outputSchematron schematron
            {
                get
                {
                    return this.schematronField;
                }
                set
                {
                    this.schematronField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        public partial class outputXml
        {

            private outputXmlXmlSchema xmlSchemaField;

            private outputXmlMessage messageField;

            /// <remarks/>
            public outputXmlXmlSchema xmlSchema
            {
                get
                {
                    return this.xmlSchemaField;
                }
                set
                {
                    this.xmlSchemaField = value;
                }
            }

            /// <remarks/>
            public outputXmlMessage message
            {
                get
                {
                    return this.messageField;
                }
                set
                {
                    this.messageField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        public partial class outputXmlXmlSchema
        {

            private string idField;

            private string versionField;

            private string targetNamespaceField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version
            {
                get
                {
                    return this.versionField;
                }
                set
                {
                    this.versionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string targetNamespace
            {
                get
                {
                    return this.targetNamespaceField;
                }
                set
                {
                    this.targetNamespaceField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        public partial class outputXmlMessage
        {

            private string textField;

            private outputXmlMessagePosition positionField;

            /// <remarks/>
            public string text
            {
                get
                {
                    return this.textField;
                }
                set
                {
                    this.textField = value;
                }
            }

            /// <remarks/>
            public outputXmlMessagePosition position
            {
                get
                {
                    return this.positionField;
                }
                set
                {
                    this.positionField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        public partial class outputXmlMessagePosition
        {

            private byte lineField;

            private byte columnField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public byte line
            {
                get
                {
                    return this.lineField;
                }
                set
                {
                    this.lineField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public byte column
            {
                get
                {
                    return this.columnField;
                }
                set
                {
                    this.columnField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
        public partial class outputSchematron
        {

            private schema schemaField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Namespace = "")]
            public schema schema
            {
                get
                {
                    return this.schemaField;
                }
                set
                {
                    this.schemaField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class schema
        {

            private schemaPhase phaseField;

            private string titleField;

            /// <remarks/>
            public schemaPhase phase
            {
                get
                {
                    return this.phaseField;
                }
                set
                {
                    this.phaseField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class schemaPhase
        {

            private schemaPhasePattern[] patternField;

            private string idField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("pattern")]
            public schemaPhasePattern[] pattern
            {
                get
                {
                    return this.patternField;
                }
                set
                {
                    this.patternField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class schemaPhasePattern
        {

            private schemaPhasePatternRule ruleField;

            private string nameField;

            private string idField;

            /// <remarks/>
            public schemaPhasePatternRule rule
            {
                get
                {
                    return this.ruleField;
                }
                set
                {
                    this.ruleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class schemaPhasePatternRule
        {

            private schemaPhasePatternRuleMessage[] messageField;

            private string contextField;

            private string idField;

            /// <remarks/>          
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("message")]
            public schemaPhasePatternRuleMessage[] message
            {
                get
                {
                    return this.messageField;
                }
                set
                {
                    this.messageField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string context
            {
                get
                {
                    return this.contextField;
                }
                set
                {
                    this.contextField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class schemaPhasePatternRuleMessage
        {

            private string textField;

            private string pathField;

            private object summaryField;

            private schemaPhasePatternRuleMessagePosition positionField;

            /// <remarks/>
            public string text
            {
                get
                {
                    return this.textField;
                }
                set
                {
                    this.textField = value;
                }
            }

            /// <remarks/>
            public string path
            {
                get
                {
                    return this.pathField;
                }
                set
                {
                    this.pathField = value;
                }
            }

            /// <remarks/>
            public object summary
            {
                get
                {
                    return this.summaryField;
                }
                set
                {
                    this.summaryField = value;
                }
            }

            /// <remarks/>
            public schemaPhasePatternRuleMessagePosition position
            {
                get
                {
                    return this.positionField;
                }
                set
                {
                    this.positionField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class schemaPhasePatternRuleMessagePosition
        {

            private byte lineField;

            private byte columnField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public byte line
            {
                get
                {
                    return this.lineField;
                }
                set
                {
                    this.lineField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public byte column
            {
                get
                {
                    return this.columnField;
                }
                set
                {
                    this.columnField = value;
                }
            }
        }

    }
}
